language: node_js

node_js:
    - "5"

env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

before_install:
    - npm install -g gulp bower
    - make ext/ipywidgets

notifications:
  email:
    on_success: change
    on_failure: always
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4
