sudo: required

language: node_js

services:
    - docker

script:
    - make test integration-test

notifications:
  email:
    on_success: change
    on_failure: always
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4
